plugin
  cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git && \
  cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=vinify && \
  cordova plugin add nl.x-services.plugins.toast && \
  cordova plugin add org.apache.cordova.network-information && \
  cordova plugin add org.apache.cordova.splashscreen && \
  cordova plugin add org.apache.cordova.statusbar